version: 1.2
workflows:
  - subclass: CWL
    primaryDescriptorPath: ./Tools/AddTogoVarAnnotation.cwl
    readMePath: README.md
    name: TogoVarAnnotation
    authors:
      - name: Dorothy DeMore Ellis
      - name: Kentaro Yamamoto
    topic: Variant Annotation

  - subclass: NFL
    primaryDescriptorPath: ./nextflow.config
    readMePath: README.md
    name: PangenomeCactus
    authors:
      - name: Pitiporn Noisagul
    topic: Germline Analysis
